name: telekinesis
description: gRPC server for Thoughts
homepage: https://github.com/arnemolland/thoughts-server

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  grpc: ^2.0.0
  protobuf: ^0.13.14
  timeago: ^2.0.17
  mongo_dart: ^0.3.5
  dotenv: ^1.0.0

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1